DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS idols;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE idols (
    id SERIAL PRIMARY KEY,
    stage_name VARCHAR(100) NOT NULL,
    real_name VARCHAR(100),
    group_name VARCHAR(100) NOT NULL,
    position VARCHAR(100),
    image_url TEXT,
    birthday DATE,
    mbti VARCHAR(100),
    nationality VARCHAR(100),
    full_profession VARCHAR(300),
    generation VARCHAR(50),
    bio TEXT,
    instagram VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE favorites (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    idol_id INTEGER NOT NULL REFERENCES idols(id) ON DELETE CASCADE,
    ranking INTEGER CHECK (ranking BETWEEN 1 AND 10),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, idol_id)
);

INSERT INTO idols (stage_name, real_name, group_name, position, image_url, birthday, mbti, nationality, full_profession, generation, bio, instagram)
VALUES
(
    'Jungkook',
    'Jeon Jung-kook',
    'BTS',
    'Main Vocalist / Lead Dancer',
    'https://cdn.shopify.com/s/files/1/0469/3927/5428/files/7788dc8fe991fcb8c684d1e462c7a61a.jpg?v=1724081793',
    '1997-09-01',
    'INTP (Logician)',
    'South Korean',
    'Singer / Songwriter',
    '3rd Gen',
    'Known for his energy and charisma on stage, and his unique fashion sense and tattoos have made him a style icon. Beyond music, Jung Kook enjoys drawing, filming, and sports, particularly boxing and fitness. Though he is said to be more introverted off stage, he transforms during performances.',
    'https://www.instagram.com/mnijungkook'
),
(
    'V',
    'Kim Tae-hyung',
    'BTS',
    'Vocalist / Dancer',
    'https://m.media-amazon.com/images/M/MV5BYjE1MWFjNWEtODI0Ny00Mjc3LWJiOTEtM2JhODE0MDEzYTdiXkEyXkFqcGc@._V1_.jpg',
    '1995-12-30',
    'INFP (Mediator)',
    'South Korean',
    'Singer / Dancer / Composer / Music Producer',
    '3rd Gen',
    'Known for his looks and has been named the most handsome face in an American survey. His photos are often compared to CGI or anime characters, earning him the nickname "CGV".',
    'https://www.instagram.com/thv'
),
(
    'Jimin',
    'Park Ji-min',
    'BTS',
    'Main Dancer / Lead Vocalist',
    'https://cdn.i-scmp.com/sites/default/files/styles/768x768/public/images/methode/2018/10/13/d79e1498-cd34-11e8-9460-2e07e264bd11_1280x720_025804.JPG?itok=kcvliGYd',
    '1995-10-13',
    'ESTP (Entrepreneur)',
    'South Korean',
    'Singer / Dancer / Songwriter / Composer',
    '3rd Gen',
    'Known for his unique voice, smooth dance moves, and stage presence. He has a background in contemporary dance and is praised for his grace and charm.',
    'https://www.instagram.com/j.m'
),
(
    'Suga / Agust D',
    'Min Yoon-gi',
    'BTS',
    'Lead Rapper / Producer',
    'https://oreosandpeanutbutter.com/wp-content/uploads/2021/05/agust-d-daechwita.jpg',
    '1993-03-09',
    'ISTP (Virtuoso)',
    'South Korean',
    'Rapper / Songwriter / Record Producer',
    '3rd Gen',
    'Born in Daegu, South Korea, Suga was an underground rapper named Gloss before joining BTS in 2013. He is known for his deep voice, sharp lyrics, and unique rap style. His solo music as Agust D often explores themes of growth, ambition, and personal struggles.',
    'https://www.instagram.com/agustd'
),
(
    'RM',
    'Kim Nam-joon',
    'BTS',
    'Leader / Main Rapper',
    'https://w0.peakpx.com/wallpaper/550/583/HD-wallpaper-kim-namjoon-army-bangtan-bt21-bts-koya.jpg',
    '1994-09-12',
    'ENFP (Campaigner)',
    'South Korean',
    'Rapper / Songwriter / Record Producer',
    '3rd Gen',
    'Known for his ability to connect with the public and is often inspired by art to write lyrics. RM is also a notable figure in the contemporary art world, collecting art and advocating for artists, especially South Korean ones.',
    'https://www.instagram.com/rkive'
),
(
    'J-Hope',
    'Jung Ho-seok',
    'BTS',
    'Main Dancer / Rapper',
    'https://gbaike-image.cdn.bcebos.com/eaf81a4c510fd9f9d72aaaba4e70c32a2834359b0ee8/eaf81a4c510fd9f9d72aaaba4e70c32a2834359b0ee8_url?x-bce-process=image/format,f_auto/resize,m_lfit,w_400,limit_1',
    '1994-02-18',
    'INFJ (Advocate)',
    'South Korean',
    'Singer / Rapper / Dancer / Songwriter / Record Producer',
    '3rd Gen',
    'Known as a member of the K-pop group BTS, managed by Big Hit Entertainment, and has gained global recognition for his energetic performances and optimistic personality. J-hope is known for his exceptional dance skills, stage presence, and creative direction.',
    'https://www.instagram.com/uarmyhope'
),
(
    'Jin',
    'Kim Seok-jin',
    'BTS',
    'Sub-Vocalist',
    'https://res.cloudinary.com/jerrick/image/upload/d_642250b563292b35f27461a7.png,f_jpg,fl_progressive,q_auto,w_1024/64aaafcbb054b0001d0782d5.jpg',
    '1992-12-04',
    'INTP (Logician)',
    'South Korean',
    'Singer / Songwriter / Actor',
    '3rd Gen',
    'Known for his soothing vocals, emotional delivery, and ability to hit high notes. He is also known for his humor, earning him the nickname "Mood Maker". Jin has released three solo tracks with BTS: "Awake" (2016), "Epiphany" (2018), and "Moon" (2020). He is known for his philanthropic work and humble nature.',
    'https://www.instagram.com/jin'
),
(
    'Jennie',
    'Kim Jennie',
    'BLACKPINK',
    'Main Rapper / Vocalist',
    'https://www.rollingstone.com/wp-content/uploads/2025/01/2409_JENNIE38564_highres-F-PC_-Cho-Gi-Seok-1.jpg',
    '1996-01-16',
    'INFJ (Advocate)',
    'South Korean',
    'Singer / Rapper / Songwriter / Actress / Fashion Icon',
    '3rd Gen',
    'Known for her charismatic stage presence, switching between fierce rapping and soft vocals. Her fashion sense blends elegance and boldness, and her association with Chanel has earned her the nickname "Human Chanel". She is a global ambassador for the brand.',
    'https://www.instagram.com/jennierubyjane'
),
(
    'Lisa',
    'Lalisa Manobal',
    'BLACKPINK',
    'Main Dancer / Lead Rapper',
    'https://voguesg.s3.ap-southeast-1.amazonaws.com/wp-content/uploads/2021/10/26165629/Lalisa-Lisa.jpg',
    '1997-03-27',
    'ESFP (Entertainer)',
    'Thai',
    'Singer / Rapper / Dancer / Model / Actress',
    '3rd Gen',
    'In 2021, Lisa became the first female K-pop solo artist to appear on Billboard Pop Songs chart with her debut solo album Lalisa. She also launched her own management company, LLOUD, in 2024.',
    'https://www.instagram.com/lalalalisa_m'
),
(
    'Rosé',
    'Roseanne Chae-young Park',
    'BLACKPINK',
    'Main Vocalist / Lead Dancer',
    'https://w0.peakpx.com/wallpaper/106/965/HD-wallpaper-rose-blackpink-blackpink-rose-kpop-on-the-ground-park-chaeyoung-rose-on-the-ground-roseanne-thumbnail.jpg',
    '1997-02-11',
    'ENFP (Campaigner)',
    'Korean-New Zealand',
    'Singer',
    '3rd Gen',
    'Known for her distinctive, airy, and raspy vocal tone, which some call the "golden voice". As the Blackpink main vocalist and lead dancer, she is also a guitarist and songwriter who plays piano. Born in Auckland, New Zealand, Rosé grew up in Melbourne, Australia, where she sang in church choirs.',
    'https://www.instagram.com/roses_are_rosie'
),
(
    'Jisoo',
    'Kim Ji-soo',
    'BLACKPINK',
    'Lead Vocalist',
    'https://m.media-amazon.com/images/M/MV5BYWI5ZmJmOGItYTkwMi00ZTdlLWE3NTctOTFhNzIxMzMxYjZkXkEyXkFqcGc@._V1_.jpg',
    '1995-01-03',
    'INTJ (Architect)',
    'South Korean',
    'Singer / Actress / Model',
    '3rd Gen',
    'Jisoo has also had success as a solo artist, releasing the EP Amortage and the chart-topping single "Earthquake" in 2025. As an actress, she has won awards and earned praise for her roles in the zombie thriller Newtopia and the fantasy film Omniscient Readers Viewpoint.',
    'https://www.instagram.com/sooyaaa__'
),
(
    'Bang Chan',
    'Christopher Chahn Bahng',
    'Stray Kids',
    'Leader / Main Producer',
    'https://assets.teenvogue.com/photos/61f2dd2fed95ef661a32349c/master/w_1600%2Cc_limit/NOEASY_BangChan_01.jpg',
    '1997-10-03',
    'ENFJ (Protagonist)',
    'Korean-Australian',
    'Singer / Rapper / Songwriter / Record Producer',
    '4th Gen',
    'Is also a member of their in-house production team, 3Racha. Chan is known for his positive messages to fans and his commitment to his bandmates. He has written and produced for other artists and is considered the architect of Stray Kids legacy.',
    'https://www.instagram.com/gnabnahc'
),
(
    'Felix',
    'Felix Yongbok Lee',
    'Stray Kids',
    'Lead Dancer / Lead Rapper',
    'https://static.wikia.nocookie.net/jyp-nation/images/b/b2/Stray_Kids_Felix_ATE_promo_photo.jpg/revision/latest?cb=20240821172510',
    '2000-09-15',
    'ENFP (Campaigner)',
    'Korean-Australian',
    'Singer / Rapper / Dancer',
    '4th Gen',
    'Known for his sharp, high-energy choreography, which incorporates his taekwondo training. He is also known for his "sunshine" personality and has been called "Stray Kids Sunshine."',
    'https://www.instagram.com/yong.lixx'
),
(
    'Hyunjin',
    'Hwang Hyun-jin',
    'Stray Kids',
    'Main Dancer / Lead Rapper',
    'https://lastfm.freetls.fastly.net/i/u/ar0/d8bb9cfe8d0d7e3edfa1f50c767c1c12.jpg',
    '2000-03-20',
    'INFP (Mediator)',
    'South Korean',
    'Singer / Rapper / Dancer / Artist',
    '4th Gen',
    'Hyunjin has also worked as a TV presenter and released solo songs he co-produced. He is known for his passion for painting and creative expression. Hyunjin has several nicknames, including "Jinnie", "Dancing Prince", and "The Prince".',
    'https://www.instagram.com/hynjinnnn'
),
(
    'Han',
    'Han Ji-sung',
    'Stray Kids',
    'Main Rapper / Lead Vocalist',
    'https://cdn.shopify.com/s/files/1/0469/3927/5428/files/Bildschirmfoto_2024-03-27_um_11.01.34_168b9ee3-e724-41d4-b1ca-b67edc3787ff.png?v=1711533764',
    '2000-09-14',
    'ISTP (Virtuoso)',
    'South Korean',
    'Singer / Rapper / Producer / Songwriter',
    '4th Gen',
    'Is also a member of their production unit, 3Racha. Han is known for his rapping, singing, and dancing, as well as his songwriting and producing contributions to Stray Kids music. In 2023, he became the youngest K-pop idol to join the Korea Music Copyright Association (KOMCA) as a full member.',
    'https://www.instagram.com/_doolsetnet'
),
(
    'Lee Know',
    'Lee Min-ho',
    'Stray Kids',
    'Main Dancer / Vocalist',
    'https://kstationtv.com/wp-content/uploads/2025/08/STRAY-KIDS-LEE-KNOW-2.jpg',
    '1998-10-25',
    'ISFP (Adventurer)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'Known for his dancing and has also released solo songs that showcase his singing talents. Lee Know is part of the Stray Kids unit DanceRacha and has choreographed his own dance cover, "Dawn", which is available on the Stray Kids YouTube channel. He has also hosted a music chart show.',
    'https://www.instagram.com/t.leeknowsaurus'
),
(
    'Seungmin',
    'Kim Seung-min',
    'Stray Kids',
    'Main Vocalist',
    'https://static.wikia.nocookie.net/stray-kids/images/6/67/Seungmin_Profile_Picture_-_South_Korea.jpg/revision/latest?cb=20260807043620',
    '2000-09-22',
    'ESFJ / ISFJ (Consul / Defender)',
    'South Korean',
    'Singer',
    '4th Gen',
    'Known for his baritone voice and ability to hit low notes. He is also the group photographer. Seungmin has clear and emotive vocals add a distinctive sound to Stray Kids music, which blends hip-hop, EDM, and pop. He also participates in songwriting and composing. Before music, Seungmin wanted to be a professional baseball player, but an injury changed his path.',
    'https://www.instagram.com/miniseungkim'
),
(
    'I.N',
    'Yang Jeong-in',
    'Stray Kids',
    'Vocalist',
    'https://static.wikia.nocookie.net/stray-kids/images/4/47/I.N_Profile_Picture_-_Japan.jpg/revision/latest/scale-to-width/360?cb=20250523103552',
    '2001-02-08',
    'ISFJ (Defender)',
    'South Korean',
    'Singer',
    '4th Gen',
    'Known for his youthful energy and genuine personality, I.N is a fan favorite and central to the Stray Kids success. His vocals are described as soft yet powerful, and fans call him "Prince of Vocals". His performances showcase a dynamic range, from powerful dance routines to emotionally charged singing.',
    'https://www.instagram.com/i.2.n.8'
),
(
    'Changbin',
    'Seo Chang-bin',
    'Stray Kids',
    'Main Rapper / Sub-Vocalist',
    'https://cdn.shopify.com/s/files/1/0469/3927/5428/files/b823c7c93b9f2a095a2af9ea16e8e9cf.jpg?v=1711448575',
    '1999-08-11',
    'ESFP (Entertainer)',
    'South Korean',
    'Rapper / Singer / Songwriter / Record Producer',
    '4th Gen',
    'Is also a member of 3Racha, an in-house production team and sub-unit of Stray Kids. Besides his contributions to Stray Kids, Changbin participated as a contestant in Show Me the Money 9 and has collaborated with various artists, including Yoon Ji-sung, Thai rappers F.Hero and Milli. Changbin became a full member of the Korea Music Copyright Association in February 2023.',
    'https://www.instagram.com/jutdwae'
),
(
    'Karina',
    'Yu Ji-min',
    'Aespa',
    'Leader / Main Dancer',
    'https://legacy.kpopping.com/f8/1/231112-aespa-Karina-Drama-at-Inkigayo-documents-1.jpeg',
    '2000-04-11',
    'ENFP (Campaigner)',
    'South Korean',
    'Singer / Rapper / Dancer',
    '4th Gen',
    'Is also a member of the supergroup Got the Beat, which debuted in 2022. Karina has described herself as "awakened Yu Jimin" and says she tries not to forget her identity as her parents daughter while living as a celebrity.',
    'https://www.instagram.com/katarinabluu'
),
(
    'Winter',
    'Kim Min-jeong',
    'Aespa',
    'Vocalist / Dancer',
    'https://static.wikia.nocookie.net/aespa/images/1/1b/Hot_Mess_Teaser_1_Winter_%285%29.jpg/revision/latest/scale-to-width/360?cb=20240610104410',
    '2001-01-01',
    'ISFP (Adventurer)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'In January 2022, she became a member of Got the Beat, a supergroup of female singers under SM.',
    'https://www.instagram.com/imwinter'
),
(
    'Giselle',
    'Kim Aeri Uchinaga',
    'Aespa',
    'Main Rapper / Sub-Vocalist',
    'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/250111_aespa_Giselle_02.jpg/960px-250111_aespa_Giselle_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail',
    '2000-10-30',
    'ENFP (Campaigner)',
    'Korean-Japanese',
    'Singer / Rapper',
    '4th Gen',
    'In December, 2021, Giselle participated in the song "Zoo" with labelmates from SM for the 2021 Winter SM Town: SMCU Express. On June 4, 2024, it was announced that Giselle will feature in artist BOL4 single "Lips" which was released on June 13. On November 14, it was announced that Giselle will feature in artist Haon single "Skrr" which is set for release on the 20th.',
    'https://www.instagram.com/aerichandesu'
),
(
    'Ningning',
    'Ning Yizhuo',
    'Aespa',
    'Main Vocalist',
    'https://www.palettehunt.com/celebrities/ningning-aespa-gallery.webp',
    '2002-10-23',
    'ENFP (Campaigner)',
    'Chinese',
    'Singer',
    '4th Gen',
    'In 2022, Ningning released an OST with fellow member Winter called "Once Again" as part of the official soundtrack of the South Korean drama Our Blues. The song charted at 119 on the Circle Digital Chart. In December, she participated in 2 tracks for the SM annual end-of-year compilation album 2022 Winter SM Town: SMCU Palace, "Time After Time" and "Good To Be Alive", with fellow SM label mates.',
    'https://www.instagram.com/imnotningning'
),
(
    'Yeonjun',
    'Choi Yeon-jun',
    'Tomorrow X Together (TXT)',
    'Main Rapper / Main Dancer',
    'https://cdn.shopify.com/s/files/1/0469/3927/5428/files/TXT-The-Name-Chapter-FREEFALL-3rd-Full-Album-Concept-Photos-documents-1_13.jpg?v=1733320183',
    '1999-09-13',
    'ENFP (Campaigner)',
    'South Korean',
    'Singer / Songwriter',
    '4th Gen',
    'Considered the main rapper of TXT, but also excels as a vocalist and dancer. Yeonjun has a unique vocal sound and expressive rap style make his parts stand out in TXT songs.',
    'https://www.instagram.com/yawnzzn'
),
(
    'Soobin',
    'Choi Soo-bin',
    'Tomorrow X Together (TXT)',
    'Leader / Vocalist',
    'https://www.palettehunt.com/celebrities/soobin-txt-hero.webp',
    '2000-12-05',
    'ISFP (The Adventurer)',
    'South Korean',
    'Singer / Songwriter',
    '4th Gen',
    'Known for his strong stage presence and expressive face, Soobin is the tallest member in TXT and the unofficial visual. He is a versatile artist who excels at both singing and dancing, and his vocals are particularly impressive on dreamier tracks like "Fairy of Shampoo" and "Blue Hour".',
    'https://www.instagram.com/page.soobin'
),
(
    'Huening Kai',
    'Kai Kamal Huening',
    'Tomorrow X Together (TXT)',
    'Vocalist / Sub-Rapper',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOcQUArvibvfqexhhs6xDHTDUSl1VgvTbydCzPe_Gd0zurYoWPpm_o8Cg&s=10',
    '2002-08-14',
    'ISTP (The Virtuoso)',
    'Korean-American',
    'Singer / Songwriter',
    '4th Gen',
    'Known for his wide vocal range, expressive performances, and ability to play multiple instruments. His singing is often featured in TXT choruses and high notes, and he sometimes raps with Yeonjun. He is also praised for his charming stage presence and versatility, and fans appreciate his kind and cheerful personality.',
    'https://www.instagram.com/kaikamal_'
),
(
    'Beomgyu',
    'Choi Beom-gyu',
    'Tomorrow X Together (TXT)',
    'Vocalist / Dancer',
    'https://pub-dc9a9c6ac2a64ba48bce426ced0ac56a.r2.dev/idols/Beomgyu/profile.jpg?v=1787617122605',
    '2001-03-13',
    'ISFJ / ENFJ (The Defender / Protagonist)',
    'South Korean',
    'Singer / Songwriter',
    '4th Gen',
    'In January 2023, Beomgyu started hosting a personal-style radio series titled Beomdio. The series was renewed for a second season which concluded in 2025 with a special offline episode at Hansung University.',
    'https://www.instagram.com/bamgyuuuu'
),
(
    'Taehyun',
    'Kang Tae-hyun',
    'Tomorrow X Together (TXT)',
    'Main Vocalist / Dancer',
    'https://lh3.googleusercontent.com/nraaUPIzTNCmLp34vsM1g7HeG8ucvid2WGGi5KyvZbKSbS5ibjLLSTS7HsZ5Wb4NCEk3-6jN8NduwITeFK04tLVbQgCDIvM2H19Z8fTUUZmZUSc=nu-e365-rj-q80-w925',
    '2002-02-05',
    'ESTP (The Entrepreneur)',
    'South Korean',
    'Singer / Songwriter',
    '4th Gen',
    'From January to May 2021, Taehyun co-hosted EBS radio show "Listen" with fellow member HueningKai. In February 2022, Taehyun featured on the single "PS5" by American singer-songwriter Salem Ilese, alongside bandmate Yeonjun and Norwegian DJ Alan Walker.',
    'https://www.instagram.com/you.th'
),
(
    'Nayeon',
    'Im Na-yeon',
    'TWICE',
    'Lead Vocalist / Lead Dancer',
    'https://static.wikia.nocookie.net/nayeon/images/8/83/Nayeon_Profile_Picture_-_South_Korea.jpg/revision/latest?cb=20240904115809',
    '1995-09-22',
    'ISTP (Virtuoso)',
    'South Korean',
    'Singer',
    '3rd Gen',
    'In 2022, she released her debut solo EP, Im Nayeon, which combines pop with genres like R&B, disco, and jazz. The EP explores themes of self-confidence, love, and overcoming challenges. Nayeon has also appeared in music videos for labelmates like GOT7 and miss A, and in television advertisements.',
    'https://www.instagram.com/nayeonyny'
),
(
    'Sana',
    'Sana Minatozaki',
    'TWICE',
    'Sub-Vocalist',
    'https://m.media-amazon.com/images/M/MV5BNTM0Mjk4YzctODM5NS00YmI2LWE4YjUtOWU0MDk4MGZhYjZhXkEyXkFqcGc@._V1_.jpg',
    '1996-12-29',
    'ENFP (Campaigner)',
    'Japanese',
    'Singer / Dancer / Actress',
    '3rd Gen',
    'Is a memeber of the Japanese subunit MiSaMo. Sana is known for her bubbly personality, positive energy, and "Sana charm". She is also the face of several brands, including Prada, and has appeared in ads.',
    'https://www.instagram.com/m.by__sana'
),
(
    'Jihyo',
    'Park Ji-hyo',
    'TWICE',
    'Leader / Main Vocalist',
    'https://static.wikia.nocookie.net/twicenation/images/5/5b/Jihyo_ENEMY_Concept_Photo.jpeg/revision/latest/scale-to-width/360?cb=20251015042601',
    '1997-02-01',
    'ESFP / ISFP (Entertainer / Adventurer)',
    'South Korean',
    'Singer',
    '3rd Gen',
    'In August 2023, she released her debut extended play, Zone, and its lead single, "Killin Me Good". Jihyo was originally named Park Ji-soo and is the second member of TWICE to debut as a solo artist. She told GRAMMY.com that she wanted to diversify her album with different genres and feels to keep listeners engaged.',
    'https://www.instagram.com/_zyozyo/'
),
(
    'Momo',
    'Momo Hirari',
    'TWICE',
    'Main Dancer / Sub-Vocalist/Rapper',
    'https://m.media-amazon.com/images/M/MV5BNzc0ODEyMDUtZTM0Mi00ZDdjLTk1ZTYtODRmZjk3ZmM1ZDk5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
    '1996-11-09',
    'INFP (Mediator)',
    'Japanese',
    'Singer / Dancer / Rapper',
    '3rd Gen',
    'Is a also memeber of the Japanese subunit MiSaMo. In Gallup Korea annual music poll for 2018, Momo was voted the 20th most popular idol in South Korea, the second highest-ranked Japanese individual in the poll, behind Twice bandmate Sana.[23] She has been one of the most popular non-Korean K-pop stars since her debut, and The Chosun Ilbo credits her popularity with helping improve relations between South Korea and Japan.',
    'https://www.instagram.com/momo'
),
(
    'Jeongyeon',
    'Yoo Jeong-yeon',
    'TWICE',
    'Lead Vocalist',
    'https://cwxzygvczfupnbvclufg.supabase.co/storage/v1/object/public/group/groups/twice/members/jeongyeon-1765414685864-TWICE_Jeongyeon_VETERAN_2_September_2024.jpg',
    '1996-11-01',
    'ISFJ (Denfender)',
    'South Korean',
    'Singer',
    '3rd Gen',
    'In October 2015, Jeongyeon officially debuted as a member of Twice with the release of their first extended play (EP), The Story Begins and its lead single "Like Ooh-Ahh". Jeongyeon and her sister co-hosted the South Korean music program Inkigayo from July 2016 to January 2017, for which they both won the Newcomer Award at the 2016 SBS Entertainment Awards.',
    'https://www.instagram.com/jy_piece'
),
(
    'Tzuyu',
    'Chou Tzu-yu',
    'TWICE',
    'Lead Dancer / Sub-Vocalist',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRizZTElstN0As_vAUNg2qlkgiNcNniL6yruIEOKKk4zohi34KxO9cOStQ&s=10',
    '1999-06-14',
    'ISFP / ISTJ (Adevnturer / Logistician)',
    'Taiwanese',
    'Singer / Dancer',
    '3rd Gen',
    'Tzuyu released her debut extended play (EP), Aboutzu, on September 6, 2024. Its lead single, "Run Away", became her first number-one single on the Billboard Taiwan Songs chart. The EP has six tracks, and includes collaborations with Peniel of BtoB and rapper pH-1',
    'https://www.instagram.com/thinkaboutzu'
),
(
    'Chaeyoung',
    'Son Chae-young',
    'TWICE',
    'Main Rapper / Sub-Vocalist',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOU7O23PZ3IuplXhzZY6HTgFr5NJhmXs9k7rG9H4cFRw&s=10',
    '1999-04-23',
    'INFP (Mediator)',
    'South Korean',
    'Singer / Songwriter / Rapper',
    '3rd Gen',
    'Chaeyoung released her debut studio album Lil Fantasy Vol. 1 and its lead single "Shoot (Firecracker)" in September 2025. The album was a critical and commercial success for Chaeyoung, debuting at number 3 on South Korean Circle Album Chart, and being named as one of the best K-pop albums of 2025 by Idology, Rolling Stone, and Billboard.',
    'https://www.instagram.com/chaeyo.0'
),
(
    'Mina',
    'Mina Sharon Myoi',
    'TWICE',
    'Main Dancer / Vocalist',
    'https://static.wikia.nocookie.net/twicenation/images/a/a4/Mina_ENEMY_Concept_Photo.jpeg/revision/latest/scale-to-width/360?cb=20251015042636',
    '1997-03-24',
    'ISFP (Adventurer)',
    'Japanese',
    'Singer / Dancer',
    '3rd Gen',
    'Is another memeber of the Japanese subunit MiSaMo, along with Sana and Momo. Debuted on Feburary 9, 2023, with the extended play titled Masterpiece. Prior to the trio debut, on January 25, they released the track "Bouquet" as part of the soundtrack of TV Asahi drama series Liaison: Kodomo no Kokoro Shinryōjo.',
    'https://www.instagram.com/mina_sr_my'
),
(
    'Dahyun',
    'Kim Da-hyun',
    'TWICE',
    'Lead Rapper / Vocalist (Sub-Vocalist)',
    'https://static.wikia.nocookie.net/twicenation/images/a/a2/Dahyun_ENEMY_Concept_Photo.jpeg/revision/latest/scale-to-width/360?cb=20251015042748',
    '1998-05-28',
    'ISFJ (Denfender)',
    'South Korean',
    'Singer / Rapper / Actress',
    '3rd Gen',
    'Dahyun made her acting debut in 2025 with the film You Are the Apple of My Eye, where she received several Best New Actress awards. She later appeared in the independent film Run to You (2025) and in the television series Love Me (2025–2026).',
    'https://www.instagram.com/dahhyunnee'
),
(
    'San',
    'Choi San',
    'Ateez',
    'Main Dancer / Lead Vocalist',
    'https://image.static.bstage.in/cdn-cgi/image/metadata=none,dpr=2,f=auto,width=190/ateez/fa151e91-a23b-4316-a9f9-a2e0d3396c55/1cec093e-5583-42c8-8417-14f68f61483b/ori.jpg',
    '1999-07-10',
    'INFP (Mediator)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'San made his acting debut in the in the 2021 KBS drama Imitation with bandmates Seonghwa, Yunho, and Jongho. He contributed his vocals to the official soundtrack of the drama as a member of "Sparkling", a fictional 4-member group. In addition to his work with Ateez, San serves as a global ambassador for Dolce & Gabbana',
    'https://www.instagram.com/choi3an'
),
(
    'Wooyoung',
    'Jung Woo-young',
    'Ateez',
    'Main Dancer / Vocalist',
    'https://static.wikia.nocookie.net/atiny/images/0/0f/ATEEZ_GOLDEN_HOUR_Part_5_Concept_Photo_2_Wooyoung_2.jpg/revision/latest?cb=20260617111331',
    '1999-11-26',
    'ISFJ / ESFJ (Defender / Consul)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'In June, 2021, Wooyoung was selected as the Artist of the Month by M2 and performed the song "Bad" by Christopher. He appeared in the first episode of Watcha Fill in the Blank documentary which explored the "real" side of K-pop artists based on a hypothetical psychological theory that the lives of modern people can be explained with nine objects.',
    'https://www.instagram.com/wooyounggg__'
),
(
    'Seonghwa',
    'Park Seong-hwa',
    'Ateez',
    'Vocalist / Rapper',
    'https://image.static.bstage.in/cdn-cgi/image/metadata=none,dpr=2,f=auto,width=380/ateez/7c6a2167-494e-4f84-8d9f-a6426a5874ac/a60cabe9-44a2-4c17-a502-8f22bb4a5333/ori.jpeg',
    '1998-04-03',
    'ESFJ (Consul)',
    'South Korean',
    'Singer / Model / Actor',
    '4th Gen',
    'In 2020, Seonghwa was cast, alongside fellow Ateez members Yunho, San and Jongho, in the KBS web drama Imitation, based on a webtoon of the same name about the lives of K-pop idols; Seonghwa played Nam Se-young, a member of the fictional group Sparkling, when the series aired in 2021.',
    'https://www.instagram.com/_starhwa_/'
),
(
    'Hongjoong',
    'Kim Hong-joong',
    'Ateez',
    'Captain (Leader) / Main Rapper',
    'https://cdn.shopify.com/s/files/1/0469/3927/5428/files/Bildschirmfoto_2024-04-10_um_16.05.08.png?v=1712758044',
    '1998-11-07',
    'INFP (Mediator)',
    'South Korean',
    'Rapper / Singer / Producer / Songwriter',
    '4th Gen',
    'From December 2019 to February 2025, Hongjoong released 8 songs by artists that he covered and interpreted in his own style (adding his own lyrics and arranging) under the project name "BY. HONGJOONG". The covered songs included "Space Oddity" by David Bowie, "Purple Rain" by Prince, "Black or White" by Michael Jackson, "모처럼" by Yoon Jong-shin, "Numb" by Linkin Park, "Lemon Tree" by Fools Garden, "Wonderwall" by Oasis, "Beat it" by Michael Jackson. As of August 2026, he has 190 songs credited under his name on The Korea Music Copyright Association (KOMCA).',
    'https://www.instagram.com/no1likeme8_8'
),
(
    'Yeosang',
    'Kang Yeo-sang',
    'Ateez',
    'Vocalist / Lead Dancer',
    'https://image.static.bstage.in/cdn-cgi/image/metadata=none,dpr=2,f=auto,width=380,height=380/ateez/17608689-cff7-4f0e-a48b-a3b2d0a91b7f/60bb8d7b-6e02-487d-8fec-1b251d3855a2/ori.jpg',
    '1999-06-15',
    'ISFJ (Defender)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'In February 2021, Kang was announced as a new co-host of SBS MTV music program The Show, alongside Kim Yo-han of WEi and Jihan of Weeekly. He hosted until December 2021, when he departed alongside his co-hosts. He returned for a second season beginning in January 2022, and was renewed for a third consecutive year in March 2023.[8] In March 2024, after approximately three years as a fixed host, Kang departed The Show. He made a one-time return as a special host in June 2024, appearing alongside bandmate Wooyoung.',
    'https://www.instagram.com/im_ovation'
),
(
    'Mingi',
    'Song Min-gi',
    'Ateez',
    'Main Rapper / Lead Dancer',
    'https://legacy.kpopping.com/bd/2/ATEEZ-Mingi-Crazy-Fom-MV-Behind-the-Scenes-with-Dispatch-documents-1.jpeg',
    '1999-08-09',
    'ENTP (Debater)',
    'South Korean',
    'Rapper / Dancer / Songwriter',
    '4th Gen',
    'Known for his fierce performances and expressive emotions, fans appreciate his ability to combine rapping and dancing to create electrifying moments. His stage presence is larger than life, and his energy is said to elevate Ateez performances. Beyond his talent, Mingi is also known for his playful personality, silly faces, and involuntary sounds.',
    'https://www.instagram.com/fixon_n_on'
),
(
    'Yunho',
    'Jeong Yun-ho',
    'Ateez',
    'Main Dancer / Vocalist',
    'https://static.wikia.nocookie.net/atiny/images/d/d3/ATEEZ_GOLDEN_HOUR_Part_4_Concept_Photo_2_Yunho_2.jpg/revision/latest?cb=20260123153629',
    '1999-03-23',
    'ENFJ (Protagonist)',
    'South Korean',
    'Singer / Dancer / Actor',
    '4th Gen',
    'On October 16, 2020, Yunho was announced as part of the cast of the KBS drama Imitation, marking his acting debut. He portrayed the second lead Lee Yu-jin, center of the boy group Sparkling. The series aired from May 7, to July 23, 2021. He also took part in the OSTs "Diamond" as a member of the fictional group Sparkling and "Like When We First Met" with actress Jung Ji-so, in their acting roles as Yu-jin and Maha respectively.',
    'https://www.instagram.com/yunou._.u'
),
(
    'Jongho',
    'Choi Jong-ho',
    'Ateez',
    'Main Vocalist / Dancer',
    'https://static.wikia.nocookie.net/atiny/images/9/9c/ATEEZ_GOLDEN_HOUR_Part_5_Concept_Photo_2_Jongho_2.jpg/revision/latest?cb=20260617111345',
    '2000-10-12',
    'ISFP (Adventurer)',
    'South Korean',
    'Singer / Actor / Dancer',
    '4th Gen',
    'Jongho made his acting debut in the 2021 KBS drama Imitation. He also contributed to multiple original soundtracks of the drama as a member of Shax, a fictional idol group in the series.',
    'https://www.instagram.com/imfinalho_'
),
(
    'Yeji',
    'Hwang Ye-ji',
    'ITZY',
    'Leader / Main Dancer',
    'https://m.media-amazon.com/images/M/MV5BYjc2MTk0MDEtNzYyNi00YjNiLTgyMzUtOWEzM2Y3YzU2MDFkXkEyXkFqcGc@._V1_.jpg',
    '2000-05-26',
    'ESFJ (Consul)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'In 2023, Yeji appeared on the cover of the April issue of W Korea. The following month, she featured on the cover of Elle Korea alongside labelmate Felix. Yeji also released her debut solo extended play (EP), Air, in March of 2025.',
    'https://www.instagram.com/yezyizhere/'
),
(
    'Yuna',
    'Shin Yu-na',
    'ITZY',
    'Lead Rapper / Lead Dancer',
    'https://xonomax.com/cdn/shop/files/752127.jpg?v=1729694722',
    '2003-12-09',
    'ENFP or ENFJ/ESFJ (Campaigner or Protagonist/Consul)',
    'South Korean',
    'Singer / Dancer / Rapper / Actress',
    '4th Gen',
    'One month after debut, she placed second in the Korean Business Research Institute brand reputation ranking for individual girl group members, behind only Blackpink member Jennie. On December 22, 2021, Yuna won the "Best Weekly Idol Individual Cam (Female)" award at the 2021 K-Champ Awards. She made her acting debut in 2026 in Undercover Miss Hong and is set to appear in My Bias, My Boss.',
    'https://www.instagram.com/igotyuandme'
),
(
    'Ryujin',
    'Shin Ryu-jin',
    'ITZY',
    'Main Rapper / Lead Dancer',
    'https://qph.cf2.quoracdn.net/main-qimg-44c1abe39de3a92867877027af9875ce-pjlq',
    '2001-04-17',
    'INTJ (Architect)',
    'South Korean',
    'Rapper / Singer / Dancer / Actress',
    '4th Gen',
    'In November 2021, she was selected as Studio Choom "Artist of the Month" and performed a solo dance cover of Billie Eilish "Therefore I am". In June 2022, Ryujin and fellow member Yeji performed Bebe Rexha "Break My Heart Myself" in Studio Choom "Mix & Max" series. On December 22, 2023, she released the music video for "Run Away", her solo track from Itzy eighth EP Born To Be.',
    'https://www.instagram.com/iamfinethankyouandryu'
),
(
    'Chaeryeong',
    'Lee Chae-ryeong',
    'ITZY',
    'Main Dancer / Sub-Vocalist/Rapper ',
    'https://static.wikia.nocookie.net/love-talk/images/f/fc/ITZY_Chaeryeong_GOLD.jpeg/revision/latest?cb=20241125034658',
    '2001-06-05',
    'INFJ (Advocate)',
    'South Korean',
    'Singer / Dancer',
    '4th Gen',
    'In August 2021, she was selected as Studio Choom "Artist of the Month" and performed a solo dance cover of Camila Cabello song called "Cry for Me". In June 2023, she also featured on the track "Doremifasolatido" from Lee Chan-hyuk album called Umbrella.',
    'https://www.instagram.com/chaerrry0'
),
(
    'Lia',
    'Choi Ji-su',
    'ITZY',
    'Main Vocalist / Sub-Rapper',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAD2x_NnvmjEuumLBPlsrn51Mat-OnXFd7YYDHVg6eN82G-Fa0_QBSgxO4&s=10',
    '2000-07-21',
    'ENFJ (Protagonist)',
    'South Korean',
    'Singer',
    '4th Gen',
    'In 2022, she released her solo song "Always Be Your Star" for the MBC series The Red Sleeve. Later that year, she recorded "Blue Flower" for the tvN series Alchemy of Souls 2, which peaked at number 184 on the Circle Chart. On May 26, 2023, Lia released "One Hundred Love" for the original soundtrack of Dr. Romantic.',
    'https://www.instagram.com/lia_loves___'
);

